name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: pwd
    - run: ls -la /home/runner/work/
    - run: echo $GITHUB_SHA
    - run: echo $GITHUB_REF
