name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: pwd
    - run: ls -la /home/runner/work/
    - run: ls -la /
    - name: smth
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: env
    - run: git remote -v
    - run: touch a.txt
    - run: git add a.txt
    - run: git status
    - run: git config --global user.email "you@example.com"
    - run: git config --global user.name "Your Name"
    - run: git commit -m 'Commit'
    - name: smth
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin master
